#AUTOGENERATED from flutter_chat_types_pydantic with pydantic_serializable & post_process.py
from typing import Optional

from pydantic import BaseModel

from user import User
from message import Message
from message import Status
from message import MessageType

class FileMessage(BaseModel):  
    author: User
    createdAt: Optional[int]
    id: str
    isLoading: Optional[bool]
    metadata: Optional[dict]
    mimeType: Optional[str]
    name: str
    remoteId: Optional[str]
    repliedMessage: Optional[Message]
    roomId: Optional[str]
    showStatus: Optional[bool]
    size: num
    status: Optional[Status]
    type: Optional[MessageType]
    updatedAt: Optional[int]
    uri: str

