#AUTOGENERATED from flutter_chat_types_pydantic with pydantic_serializable & post_process.py
from typing import Optional

from pydantic import BaseModel

from message import Message
from preview_data import PreviewData

class PartialText(BaseModel):  
    metadata: Optional[dict]
    previewData: Optional[PreviewData]
    repliedMessage: Optional[Message]
    text: str

