#AUTOGENERATED from flutter_chat_types_pydantic with pydantic_serializable & post_process.py
from typing import Optional

from pydantic import BaseModel

from message import Message

class PartialAudio(BaseModel):  
    duration: Duration
    metadata: Optional[dict]
    mimeType: Optional[str]
    name: str
    repliedMessage: Optional[Message]
    size: float
    uri: str
    waveForm: Optional[list[float]]

